eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linlp0617/test.git
          searchPaths: helloworldConfig
  application:
    name: config-server